# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 19:59
from __future__ import unicode_literals

import WebApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_description', models.CharField(max_length=100)),
                ('book_file', models.FileField(upload_to=WebApp.models.generate_url)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
